version: '1'

volumes:
  data:

services:

  web:
    build: .
    ports:
      - "8000:5000"
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
  myapp:
    image: [YOUR-APP-IMAGE]